#ifndef LIBP2P_ERRORS_H
#define LIBP2P_ERRORS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    LP2P_OK = 0,
    LP2P_ERR_NOMEM,
    LP2P_ERR_INVALID_ARG,
    LP2P_ERR_INVALID_MULTIADDR,
    LP2P_ERR_INVALID_KEY,
    LP2P_ERR_CRYPTO,
    LP2P_ERR_HANDSHAKE_FAILED,
    LP2P_ERR_NEGOTIATION_FAILED,
    LP2P_ERR_PROTOCOL_NOT_SUPPORTED,
    LP2P_ERR_PROTOCOL,
    LP2P_ERR_CONNECTION_REFUSED,
    LP2P_ERR_CONNECTION_CLOSED,
    LP2P_ERR_BUSY,
    LP2P_ERR_STREAM_RESET,
    LP2P_ERR_TIMEOUT,
    LP2P_ERR_EOF,
    LP2P_ERR_WOULD_BLOCK,
    LP2P_ERR_NOT_FOUND,
    LP2P_ERR_TRANSPORT,
    LP2P_ERR_MUX,
    LP2P_ERR_PEER_ID_MISMATCH,
    LP2P_ERR_MAX_CONNECTIONS,
    LP2P_ERR_ALREADY_CONNECTED,
    LP2P_ERR_INTERNAL,
} lp2p_err_t;

const char *lp2p_strerror(lp2p_err_t err);

#ifdef __cplusplus
}
#endif

#endif /* LIBP2P_ERRORS_H */
