find_path(LIBUV_INCLUDE_DIR NAMES uv.h)
find_library(LIBUV_LIBRARY NAMES uv libuv)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Libuv DEFAULT_MSG LIBUV_LIBRARY LIBUV_INCLUDE_DIR)
set(LIBUV_LIBRARIES    ${LIBUV_LIBRARY})
set(LIBUV_INCLUDE_DIRS ${LIBUV_INCLUDE_DIR})
mark_as_advanced(LIBUV_INCLUDE_DIR LIBUV_LIBRARY)
